# Generated by Django 2.2.6 on 2019-11-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIB_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redaction',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
