# Generated by Django 2.2.6 on 2019-11-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIB_APP', '0002_auto_20191112_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redaction',
            name='name',
            field=models.CharField(error_messages={'unique': 'Такая редакция уже существует'}, max_length=50, unique=True),
        ),
    ]
