# Generated by Django 2.2.6 on 2019-11-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIB_APP', '0005_auto_20191112_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookholder',
            name='birth_date',
            field=models.DateField(error_messages={'input_formats': 'Введите корректную дату и попробуйте снова!'}),
        ),
    ]
