# Generated by Django 2.2.6 on 2019-11-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIB_APP', '0007_auto_20191113_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='country',
            field=models.CharField(error_messages={'max_length': 'Только 2 буквы!'}, max_length=2),
        ),
        migrations.AlterField(
            model_name='redaction',
            name='name',
            field=models.CharField(error_messages={'unique': 'Такая редакция уже существует!'}, max_length=50, unique=True),
        ),
    ]
