# Generated by Django 2.2.6 on 2019-11-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIB_APP', '0008_auto_20191113_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookholder',
            name='birth_date',
            field=models.DateField(error_messages={'invalid_date': 'Введите корректную дату и попробуйте снова!'}),
        ),
    ]
